/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.du.ogc.ais.examples.GUI;

import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.avlist.AVKey;
import gov.nasa.worldwind.layers.Layer;
import gov.nasa.worldwind.layers.LayerList;
import gov.nasa.worldwind.util.layertree.LayerTree;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JDialog;

/**
 *
 * @author Jing
 */
public class LayerDeletePanel extends javax.swing.JPanel {

    LayerTree layerTree;
    protected final WorldWindow wwd;
    protected boolean includeHiddenLayers = false;
    private JDialog dialog;
    private boolean confirmed = false;
    private ArrayList<String> layernames = new ArrayList<String>();

    class LayerListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent e) {
            JCheckBox jcb = (JCheckBox) e.getItem();
            if (jcb.isSelected()) {
                if (!layernames.contains(jcb.getText())) {
                    layernames.add(jcb.getText());
                }
            } else {
                if (layernames.contains(jcb.getText())) {
                    layernames.remove(jcb.getText());
                }
            }
        }
    }

    /**
     * Creates new form LayerDeletePanel
     */
    public LayerDeletePanel(WorldWindow wwd, LayerTree layerTree) {
        initComponents();
        this.wwd = wwd;
        this.layerTree = layerTree;
        this.CreateLayerItems();
    }

    private void CreateLayerItems() {
        this.jLayerPanel.removeAll();
        this.jLayerPanel.setLayout(new GridLayout(0, 1, 0, 15));
        LayerList layerList = this.wwd.getModel().getLayers();
        for (Layer layer : layerList) {
            
                if (this.CheckOptionalLayer(layer)) {
                    //add jcheckbox
                    JCheckBox jcb = new JCheckBox();
                    jcb.setText(layer.getName());
                    jcb.addItemListener(new LayerListener());
                    jcb.setSelected(false);
                    this.jLayerPanel.add(jcb);
                }
            
        }
    }

    public ArrayList<String> GetDeleteLayers() {
        return this.layernames;
    }

    public boolean isIncludeHiddenLayers() {
        return this.includeHiddenLayers;
    }



    protected boolean CheckOptionalLayer(Layer layer) {
        String[] optionallayer = {"Stars", "Atmosphere",
            "USDA", "Virutal", "USGS", "Open Street Map",
            "Place Names", "World Map", "Scale bar", "Compass", "Layer Control", "Layers"};
        for (int i = 0; i < optionallayer.length; i++) {
            if (layer.getName().contains(optionallayer[i])) {
                return false;
            }
        }
        return true;
    }

    public void setDialog(JDialog dialog) {
        this.dialog = dialog;
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLayerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayerPanelLayout = new javax.swing.GroupLayout(jLayerPanel);
        jLayerPanel.setLayout(jLayerPanelLayout);
        jLayerPanelLayout.setHorizontalGroup(
            jLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        jLayerPanelLayout.setVerticalGroup(
            jLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jLayerPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Choose layers to Delete");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (dialog != null) {
            confirmed = true;
            dialog.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
               if (dialog != null) {
            confirmed = false;
            dialog.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jLayerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
